spring:
  application:
    name: deal
  datasource:
    url: jdbc:postgresql://localhost:5432/neoflexbd
    username: neoflexuser
    password: neoflex
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none


server:
  port: 8011

logging:
  level:
    liquibase: DEBUG
