spring:
  application:
    name: apigateway

server:
  port: 8015

services:
  calculator:
    url: http://localhost:8010
  deal:
    url: http://localhost:8011
  statement:
    url: http://localhost:8012

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    ru.neoflex.gateway: DEBUG