spring:
  application:
    name: calculator

server:
  port: 8010

services:
  calculator:
    url: http://localhost:8081

  deal:
    url: http://localhost:8082

  statement:
    url: http://localhost:8083