openapi: 3.0.2
info:
  title: Credit Calculator API
  version: 1.0.0
  description: Микросервис для расчета кредитных предложений с разными условиями и параметров кредита.

paths:
  /calculator/offers:
    post:
      summary: Прескоринг и расчет 4 вариантов предложений
      operationId: creditOffers
      tags:
        - Calculator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './common-components.yaml#/components/schemas/LoanStatementRequestDto'
      responses:
        '200':
          description: Список из 4-х LoanOfferDto (от худшего к лучшему)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './common-components.yaml#/components/schemas/LoanOfferDto'

  /calculator/calc:
    post:
      summary: Полный скоринг и расчет кредита для клиента
      description: Эндпоинт для расчёта кредита. Данные проходят валидацию и скоринг.
      operationId: creditCalculation
      tags:
        - Calculator
      requestBody:
        description: Информация о клиенте и запрашиваемом кредите
        required: true
        content:
          application/json:
            schema:
              $ref: './common-components.yaml#/components/schemas/ScoringDataDto'
      responses:
        '200':
          description: Полный расчет кредита с графиком платежей
          content:
            application/json:
              schema:
                $ref: './common-components.yaml#/components/schemas/CreditDto'
        '400':
          description: Ошибка валидации или провал скоринга
          content:
            application/json:
              schema:
                $ref: './common-components.yaml#/components/schemas/CreditDto'
              example: {}
