openapi: 3.0.3
info:
  title: Deal Service API
  version: 1.0.0
  description: API для управления процессом оформления кредитных сделок.

paths:
  /deal/statement:
    post:
      summary: Расчёт возможных условий кредита
      operationId: createStatement
      tags:
        - Deal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './common-components.yaml#/components/schemas/LoanStatementRequestDto'
      responses:
        '200':
          description: Список из 4 предложений, отсортированных от худшего к лучшему
          content:
            application/json:
              schema:
                type: array
                nullable: true
                items:
                  $ref: './common-components.yaml#/components/schemas/LoanOfferDto'

  /deal/offer/select:
    post:
      summary: Выбор одного из предложений
      operationId: selectOffer
      tags:
        - Deal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './common-components.yaml#/components/schemas/LoanOfferDto'
      responses:
        '200':
          description: Предложение успешно выбрано

  /deal/calculate/{statementId}:
    post:
      summary: Завершение регистрации и полный подсчёт кредита
      operationId: calculateCredit
      tags:
        - Deal
      parameters:
        - name: statementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinishRegistrationRequestDto'
      responses:
        '200':
          description: Кредит успешно рассчитан и сохранен

  /deal/document/{statementId}/send:
    post:
      summary: Запрос на отправку документов
      operationId: sendDocuments
      tags:
        - Deal
        - Documents
      parameters:
        - name: statementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Документы отправлены

  /deal/document/{statementId}/sign:
    post:
      summary: Запрос на подписание документов
      operationId: signDocuments
      tags:
        - Deal
        - Documents
      parameters:
        - name: statementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Сформирован запрос на подписание

  /deal/document/{statementId}/code:
    post:
      summary: Подписание документов (ввод кода)
      operationId: documentCodePass
      tags:
        - Deal
        - Documents
      parameters:
        - name: statementId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sescode:
                  type: string
              required:
                - sescode
      responses:
        200:
          description: Документы успешно подписаны

components:
  schemas:
    FinishRegistrationRequestDto:
      type: object
      properties:
        gender:
          $ref: './common-components.yaml#/components/schemas/Genders'
        maritalStatus:
          $ref: './common-components.yaml#/components/schemas/MaritalStatus'
        dependentAmount:
          description: Число иждивенцев
          type: integer
          example: 3
        passportIssueDate:
          description: Дата выдачи паспорта
          type: string
          format: date
          example: 2014-01-01
        passportIssueBrach:
          description: Место выдачи паспорта
          type: string
          example: MVD
        employment:
          $ref: './common-components.yaml#/components/schemas/EmploymentDto'
        accountNumber:
          description: Номер счёта
          type: string
          example: 15235434

    Passport:
      type: object
      properties:
        passportUuid:
          type: string
          format: uuid
        series:
          description: Серия паспорта клиента
          type: string
          pattern: '^\d{4}$'
          example: 1234
        number:
          description: Номер паспорта клиента
          type: string
          pattern: '^\d{6}$'
          example: 123456
        issueBranch:
          description: Место выдачи паспорта
          type: string
          example: MVD
        issueDate:
          description: Дата выдачи паспорта
          type: string
          format: date
          example: 2014-01-01

    StatementStatusHistoryDto:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ApplicationStatus'
        time:
          type: string
          format: date-time
        changeType:
          $ref: '#/components/schemas/ChangeType'

    ApplicationStatus:
      description: Статус заявки
      type: string
      enum:
        - PREAPPROVAL
        - APPROVED
        - CC_DENIED
        - CC_APPROVED
        - PREPARE_DOCUMENTS
        - DOCUMENT_CREATED
        - CLIENT_DENIED
        - DOCUMENT_SIGNED
        - CREDIT_ISSUED

    CreditStatus:
      description: Статус кредита
      type: string
      enum:
        - CALCULATED
        - ISSUED

    ChangeType:
      description: Режим изменения истории статусов
      type: string
      enum:
        - AUTOMATIC
        - MANUAL
